### ISSUE TITLE
Range selection

### ISSUE THREAD

**Issue by Leovenn** [Artem9989/vue-three-round-slider#3]
Range selection cannot be dragged to a minimum or maximum value

**Comment by Leovenn** [comment]
![image](https://github.com/Artem9989/vue-three-round-slider/assets/57058087/9b9ed0f4-feda-4a71-bef0-55e4667192be)

**Comment by Artem9989** [comment]
Hello, have you tried setting min?
If I misunderstood you, describe the problem in more detail
```
      <round-slider
        rangeColor="#125896"
        circleShape="half-left"
        v-model="childValue"
        min="360"
        max="720"
      />
```
так же вам может помочь
```
      <round-slider
        rangeColor="#72222"
        start-angle="180"
        end-angle="+180"
        v-model="childValue"
        max="123"
      />
```

**Comment by Leovenn** [comment]
I'll give you an online example where you can see if you can manually drag it to 0-1439 [demo](https://codesandbox.io/s/round-slider-with-ticks-forked-mbunbh?file=/src/components/SliderDemo.vue)

**Comment by Artem9989** [comment]
Thank you I did it
